### PR TITLE
Helping you start your first PR

### PR DESCRIPTION
**Pull request by edamame852**

### CODE REVIEW

**Comment by edamame852** [comment]
You can choose to either delete your `oliver` branch or not
What I usually do is I keep it

**Comment by edamame852** [comment]
The reason why is, typically as a developer, we work in parallel on each component and merge it back together into main. 
Aside from you, usually, no one will touch your `oliver` branch, because I will have my own `milton` branch

Hope this is clear ~ :)

**Comment by 951002** [comment]
我知道了，謝謝你。
另外，我現在有個問題想請教您，就是我該如何開始我真正的first project，因為我也去了 youtube 看了很多相關的影片，但似乎還是毫無頭緒，不知該如何開始

**Comment by edamame852** [comment]
It depends on what type of projects you want to try, the options are limitless
There's a few off the top of my head...
- Python Scaffolding = making a python binary (the hardest but the most useful) (I would say not many people know how to do this)
- Data science analytic projects (Easiest but also not as impressive to other people)
- Frontend project = making your own website (achievable with node, jekyll, spyinx...)
- Backend project = creating your own swagger UI project (for api calls) (achievable with java spring boot, rust, python fastAPI)

**Comment by edamame852** [comment]
Which one do you feel like doing the most ?

**Comment by edamame852** [comment]
If we want to learn something together I think we can try doing a backend project together using Java and using the springboot framework

**Comment by 951002** [comment]
抱歉，這麼慢才回復你。
我認為我們可以一起試試 backend project，假如方便的話，我也想學習如何設計一個屬於自己的網站

**Comment by 951002** [comment]
I can't wait to do it!

**Comment by edamame852** [comment]
Shall we do a call Thursday night?

**Comment by 951002** [comment]
No problem.

**Comment by edamame852** [comment]
Let me set up a call and share it here

**Comment by edamame852** [comment]
Backend call
Thursday, May 23 · 9–10 PM
Google Meet joining info
Video call link: https://meet.google.com/uhx-onnh-kqq

**Pull request merged**
